/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include<stdint.h>

#define RCC_BASE_ADDR              0x40023800UL

#define RCC_CR_REG_ADDR            RCC_BASE_ADDR

#define RCC_CFGR_REG_OFFSET        0x08UL

#define RCC_CFGR_REG_ADDR          (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET )

#define GPIOA_BASE_ADDR            0x40020000UL

#define RCC_CR_HSEON_RDY_MASK      0x01<<17

int main(void)
{




    uint32_t *pRccCrReg = (uint32_t*) RCC_CR_REG_ADDR;
    //1-Enable HSE Bypass
    *pRccCrReg |= 0x01 << 18; //Set 18 bit position
    // 2. Configure HSE ON to start HSE
    *pRccCrReg |= 0x01 << 16; //Set 16 bit position

    uint32_t *pRccCfgrReg =  (uint32_t*) RCC_CFGR_REG_ADDR;

    //3. Switch system clock to HSE

    *pRccCfgrReg |= 0x01 << 0;


	//4. Configure the RCC_CFGR MCO1 bit fields to select HSE as clock source
	*pRccCfgrReg &= ~(0x3 << 21); //clear 21 and 22 bit positions
	*pRccCfgrReg |= 0x01 << 22; //Set 22 bit position


	//Configure MCO1 pre-scaler
	//*pRccCfgrReg |= ( 1 << 25);
	*pRccCfgrReg |= ( 1 << 26);

	//2. Configure PA8 to AF0 mode to behave as MCO1 signal
/*
 * You are not expected to understand the below codes for the time being
 * because these codes are related to GPIO configurations,
 * which will be covered in later sections of this course.
 */

	//a ) Enable the peripheral clock for GPIOA peripheral

	 uint32_t *pRCCAhb1Enr = (uint32_t*)(RCC_BASE_ADDR + 0x30);
	*pRCCAhb1Enr |= ( 1 << 0); //Enable GPIOA peripheral clock

	//b ) Configure the mode of GPIOA pin 8 as alternate function mode

	uint32_t *pGPIOAModeReg = (uint32_t*)(GPIOA_BASE_ADDR + 00);
	*pGPIOAModeReg &= ~( 0x3 << 16); //clear
	*pGPIOAModeReg |= ( 0x2 << 16);  //set

	//c ) Configure the alternation function register to set the mode 0 for PA8

	uint32_t *pGPIOAAltFunHighReg = (uint32_t*)(GPIOA_BASE_ADDR + 0x24);
	*pGPIOAAltFunHighReg &= ~( 0xf << 0);

	for(;;);
}
