/*
 * mainGpioInterrupt.c
 *
 *  Created on: 26 Jul 2020
 *      Author: ROG
 */
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
 */

#include "Stm32f767.h"
#include "stm32F7xx_gpio.h"
#include <string.h>

void delay(uint32_t duration)
{
	for(int32_t i = 0; i<(duration*10);i++);
}
int main(void)
{
	GPIO_Handle_t GpioBtn, GpioLed;
	memset(&GpioBtn,0,sizeof(GpioBtn));
	memset(&GpioLed,0,sizeof(GpioLed));
	//Gpio config for LED
	GpioLed.pGPIOx = GPIOB;
	GpioLed.GPIO_PinConfig.PinNum = GPIO_PIN7 ;//PIN7;
	GpioLed.GPIO_PinConfig.PinMode = GPIO_OUTPUT;
	GpioLed.GPIO_PinConfig.PinSpeed = GPIO_SPEED_VERY_HIGH;
	GpioLed.GPIO_PinConfig.PinOPType = GPIO_PUSH_PULL;
	GpioLed.GPIO_PinConfig.PinPupDr = GPIO_PUPDR_NOPULL;
	PeriphClckControl(GPIOB,ENABLE);
	GPIO_Init(&GpioLed);
	//GPIO configure for the button
	GpioBtn.pGPIOx = GPIOC;
	GpioBtn.GPIO_PinConfig.PinNum = GPIO_PIN13 ;
	GpioBtn.GPIO_PinConfig.PinMode = GPIO_IT_FALLING;
	GpioBtn.GPIO_PinConfig.PinSpeed = GPIO_SPEED_VERY_HIGH;
	GpioBtn.GPIO_PinConfig.PinPupDr = GPIO_PUPDR_NOPULL;
	PeriphClckControl(GPIOC,ENABLE);
	GPIO_Init(&GpioBtn);;

	//Configure IRQ
	GPIO_IRQITConfig( EXTI15_10_IRQn, ENABLE);
	//void GPIO_IRQHandler(uint8_t PinNumber);
	IRQPriorityConfig(EXTI15_10_IRQn, 5);

	while(1)
	{

	}

}
void EXTI15_10_IRQHandler(void)
{
	delay(1000);
	GPIO_IRQHandler(GPIO_PIN13);
	ToggleOutputPin(GPIOB,GPIO_PIN7);

}
void EXTI0_IRQHandler()
{
	GPIO_IRQHandler(0);
}
