/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
*/

#include "Stm32f767.h"
#include "stm32F7xx_gpio.h"

void delay(uint32_t duration)
{
	for(int32_t i = 0; i<(duration*10);i++);
}
int main(void)
{
GPIO_Handle_t GpioLed;
GpioLed.pGPIOx = GPIOB;
GpioLed.GPIO_PinConfig.PinNum = GPIO_PIN7 ;//PIN7;
GpioLed.GPIO_PinConfig.PinMode = GPIO_OUTPUT;
GpioLed.GPIO_PinConfig.PinSpeed = GPIO_SPEED_VERY_HIGH;
GpioLed.GPIO_PinConfig.PinOPType = GPIO_PUPDR_PULLUP;
GpioLed.GPIO_PinConfig.PinPupDr = GPIO_PUPDR_NOPULL;
PeriphClckControl(GPIOB,ENABLE);
//GPIOB_PERIPH_CLCK_EN();
GPIO_Init(&GpioLed);

while(1)
{
	ToggleOutputPin(GPIOB,GPIO_PIN7);
	delay(500000);
}
	//for(;;);
}
void EXTI0_IRQHandler()
{
	GPIO_IRQHandler(0);
}
